name: Set Environment Variables

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  set_env_variables:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: set_env
        run: |
          branch="${{ github.event.inputs.branch }}"
          case $branch in
            main)
              HOST="HOST"
              USERNAME="USERNAME"
              PEM_KEY="PEM_KEY"
              ;;
            action)
              HOST="HOST_2"
              USERNAME="USERNAME_2"
              PEM_KEY="PEM_KEY_2"
              ;;
            *)
              echo "Invalid branch name: $branch"
              exit 1
              ;;
          esac
          echo "HOST=$HOST"
          echo "USERNAME=$USERNAME"
          echo "PEM_KEY=$PEM_KEY"