name: Remote SSH Command

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  server_job_1:
    name: Server 1
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == 'main' # Replace with your branch name
    steps:
      - name: Execute on Server 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_1 }}
          username: ${{ secrets.USERNAME_1 }}
          key: ${{ secrets.PEM_KEY_1 }}
          port: 22
          script: |
            pwd
            ls
            bash script.sh

  server_job_2:
    name: Server 2
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == 'action' # Replace with your branch name
    steps:
      - name: Execute on Server 2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_2 }}
          username: ${{ secrets.USERNAME_2 }}
          key: ${{ secrets.PEM_KEY_2 }}
          port: 22
          script: |
            pwd
            ls
            bash script.sh