name: Remote SSH Command

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  execute_remote_command:
    name: Execute Remote SSH Command
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          branches=(action main) # Define the branch names
          branch="${{ github.event.inputs.branch }}"
          # Create a map of branch configurations
          declare -A branch_configs
          branch_configs["action"]="HOST USERNAME PEM_KEY"
          branch_configs["main"]="HOST_2 USERNAME_2 PEM_KEY_2"
          
          # Set environment variables based on the branch name
          if [[ "${branches[*]}" =~ "${branch}" ]]; then
            echo "Setting environment variables for '${branch}' branch"
            for config_var in ${branch_configs["$branch"]}; do
              secret_var="${config_var// /_}"
              echo "$config_var=${{ secrets.${secret_var} }}" >> $GITHUB_ENV
            done
          else
            echo "Invalid branch name: ${branch}"
            exit 1
          fi

      - name: Execute on the Target Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.PEM_KEY }}
          port: 22
          script: |
            ls
            script.sh