name: Set Environment Variables

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  set_env_variables:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: set_env
        run: |
          branch="${{ github.event.inputs.branch }}"
          case $branch in
            main)
              IP_SECRET="VM_MAIN_IP"
              USER_SECRET="VM_MAIN_USERNAME"
              PEM_SECRET="VM_MAIN_PEM"
              ;;
            prod)
              IP_SECRET="VM_PROD_IP"
              USER_SECRET="VM_PROD_USERNAME"
              PEM_SECRET="VM_PROD_PEM"
              ;;
            *)
              echo "Invalid branch name: $branch"
              exit 1
              ;;
          esac
          echo "HOSTNAME_SECRET=$IP_SECRET"
          echo "USER_SECRET=$USER_SECRET"
          echo "PEM_KEY_SECRET=$PEM_SECRET"