name: Remote SSH Command

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  execute_remote_command:
    name: Execute Remote SSH Command
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          branches=(action main) # Define the branch names
          branch="${{ github.event.inputs.branch }}"
          
          if [[ "$branch" == "action" ]]; then
            echo "Setting environment variables for 'action' branch"
            echo "HOST=${{ secrets.HOST_1 }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.USERNAME_1 }}" >> $GITHUB_ENV
            echo "PEM_KEY=${{ secrets.PEM_KEY_1 }}" >> $GITHUB_ENV
          elif [[ "$branch" == "main" ]]; then
            echo "Setting environment variables for 'main' branch"
            echo "HOST=${{ secrets.HOST_2 }}" >> $GITHUB_ENV
            echo "USER=${{ secrets.USERNAME_2 }}" >> $GITHUB_ENV
            echo "PEM_KEY=${{ secrets.PEM_KEY_2 }}" >> $GITHUB_ENV
          else
            echo "Invalid branch name: $branch"
            exit 1
          fi

      - name: Execute on the Target Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.PEM_KEY }}
          port: 22
          script: ls
