name: Set Environment Variables

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  set_env_variables:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: set_env
        run: |
          branch="${{ github.event.inputs.branch }}"
          # Construct secret names based on the branch
          IP_SECRET="VM_${branch}_IP"
          USERNAME_SECRET="VM_${branch}_USERNAME"
          PEM_SECRET="VM_${branch}_PEM"

          echo "Setting environment variables for '$branch' branch"
          echo "::set-env name=HOSTNAME::${{ secrets[$IP_SECRET] }}"
          echo "::set-env name=USER::${{ secrets[$USERNAME_SECRET] }}"
          echo "::set-env name=PEM_KEY::${{ secrets[$PEM_SECRET] }}"