name: Remote SSH Command

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  execute_remote_command:
    name: Execute Remote SSH Command
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['action', 'main']
        host: ['HOST', 'HOST_2']
        username: ['USERNAME', 'USERNAME_2']
        pem_key: ['PEM_KEY', 'PEM_KEY_2']

    steps:
      - name: Set Environment Variables
        run: |
          echo "Setting environment variables for ${{ matrix.branch }} branch"
          echo "HOST=${{ secrets[matrix.host] }}" >> $GITHUB_ENV
          echo "USER=${{ secrets[matrix.username] }}" >> $GITHUB_ENV
          echo "PEM_KEY=${{ secrets[matrix.pem_key] }}" >> $GITHUB_ENV

      - name: Execute on the Target Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.PEM_KEY }}
          port: 22
          script: |
            # Your commands to execute on the selected server
